import type { Product, Category, Review } from '../types';

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'Electronics',
    name_ar: 'إلكترونيات',
    slug: 'electronics',
    description: 'Latest gadgets and electronic devices',
    description_ar: 'أحدث الأجهزة والإلكترونيات',
    image: 'https://images.unsplash.com/photo-1498049794581-671d7a4e9d0c?w=600&q=80',
    products_count: 6,
  },
  {
    id: 2,
    name: 'Fashion',
    name_ar: 'أزياء',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    description_ar: 'ملابس وإكسسوارات عصرية',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80',
    products_count: 4,
  },
  {
    id: 3,
    name: 'Home & Living',
    name_ar: 'المنزل والمعيشة',
    slug: 'home-living',
    description: 'Everything for your home',
    description_ar: 'كل ما تحتاجه لمنزلك',
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80',
    products_count: 3,
  },
  {
    id: 4,
    name: 'Sports',
    name_ar: 'رياضة',
    slug: 'sports',
    description: 'Gear up for your workouts',
    description_ar: 'تجهيز لممارسة الرياضة',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&q=80',
    products_count: 3,
  },
  {
    id: 5,
    name: 'Beauty',
    name_ar: 'جمال',
    slug: 'beauty',
    description: 'Skincare and cosmetics',
    description_ar: 'العناية بالبشرة ومستحضرات التجميل',
    image: 'https://images.unsplash.com/photo-1596462502278-916a0ba43185?w=600&q=80',
    products_count: 2,
  },
  {
    id: 6,
    name: 'Books',
    name_ar: 'كتب',
    slug: 'books',
    description: 'Bestsellers and classics',
    description_ar: 'الأكثر مبيعاً والكلاسيكيات',
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&q=80',
    products_count: 2,
  },
];

const img = (url: string) => JSON.stringify([url]);

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Wireless Noise-Cancelling Headphones',
    name_ar: 'سماعات لاسلكية بتقنية إلغاء الضوضاء',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Experience premium sound with active noise cancellation, 30-hour battery life, and ultra-comfortable ear cushions. Perfect for travel and focused work.',
    description_ar: 'استمتع بصوت فاخر مع إلغاء الضوضاء النشط، عمر بطارية 30 ساعة، ووسائد أذن فائقة الراحة. مثالي للسفر والعمل المركّز.',
    price: 299.99,
    compare_price: 399.99,
    images: img('https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80'),
    category_id: 1,
    category_name: 'Electronics',
    category_name_ar: 'إلكترونيات',
    category_slug: 'electronics',
    stock: 45,
    rating: 4.8,
    reviews_count: 124,
    featured: 1,
    specifications: JSON.stringify({ 'Battery': '30 hours', 'Bluetooth': '5.2', 'Weight': '250g', 'Warranty': '2 years' }),
    created_at: '2024-01-15',
  },
  {
    id: 2,
    name: 'Smart Watch Series 7',
    name_ar: 'ساعة ذكية الإصدار 7',
    slug: 'smart-watch-series-7',
    description: 'Track your fitness, heart rate, sleep, and notifications. Water-resistant up to 50m with always-on display.',
    description_ar: 'تتبع لياقتك ومعدل ضربات القلب والنوم والإشعارات. مقاومة للماء حتى 50 متر مع شاشة دائمة العرض.',
    price: 249.00,
    compare_price: 299.00,
    images: img('https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'),
    category_id: 1,
    category_name: 'Electronics',
    category_name_ar: 'إلكترونيات',
    category_slug: 'electronics',
    stock: 78,
    rating: 4.7,
    reviews_count: 89,
    featured: 1,
    specifications: JSON.stringify({ 'Display': '1.9" AMOLED', 'Battery': '18 hours', 'Water': '50m', 'Connectivity': 'WiFi + LTE' }),
    created_at: '2024-02-10',
  },
  {
    id: 3,
    name: 'Professional Camera DSLR',
    name_ar: 'كاميرا احترافية DSLR',
    slug: 'professional-camera-dslr',
    description: '24.2MP sensor, 4K video recording, fast autofocus, and a versatile 18-55mm lens included.',
    description_ar: 'مستشعر 24.2 ميجابكسل، تصوير 4K، تركيز تلقائي سريع، مع عدسة 18-55 مم متعددة الاستخدامات.',
    price: 899.00,
    compare_price: 1099.00,
    images: img('https://images.unsplash.com/photo-1502920917128-1aaeba762f71?w=800&q=80'),
    category_id: 1,
    category_name: 'Electronics',
    category_name_ar: 'إلكترونيات',
    category_slug: 'electronics',
    stock: 23,
    rating: 4.9,
    reviews_count: 56,
    featured: 1,
    specifications: JSON.stringify({ 'Sensor': '24.2MP APS-C', 'Video': '4K 60fps', 'ISO': '100-25600', 'Lens': '18-55mm' }),
    created_at: '2024-03-05',
  },
  {
    id: 4,
    name: 'Mechanical Gaming Keyboard',
    name_ar: 'لوحة مفاتيح ميكانيكية للألعاب',
    slug: 'mechanical-gaming-keyboard',
    description: 'RGB backlight, blue switches, full anti-ghosting, and a durable aluminum frame for serious gamers.',
    description_ar: 'إضاءة RGB، مفاتيح زرقاء، anti-ghosting كامل، وإطار ألمنيوم متين لللاعبين المحترفين.',
    price: 119.99,
    compare_price: 149.99,
    images: img('https://images.unsplash.com/photo-1587829741301-dc798b83add8?w=800&q=80'),
    category_id: 1,
    category_name: 'Electronics',
    category_name_ar: 'إلكترونيات',
    category_slug: 'electronics',
    stock: 120,
    rating: 4.6,
    reviews_count: 210,
    featured: 0,
    specifications: JSON.stringify({ 'Switches': 'Blue', 'Backlight': 'RGB', 'Connection': 'Wired USB', 'Layout': 'QWERTY' }),
    created_at: '2024-03-20',
  },
  {
    id: 5,
    name: '4K Ultra HD Smart TV 55"',
    name_ar: 'تلفاز ذكي 4K 55 بوصة',
    slug: '4k-ultra-hd-smart-tv-55',
    description: 'Stunning 4K HDR display with built-in streaming apps, voice remote, and Dolby Atmos sound.',
    description_ar: 'شاشة 4K HDR مذهلة مع تطاقات بث مدمجة، ريموت صوتي، وصوت Dolby Atmos.',
    price: 549.00,
    compare_price: 699.00,
    images: img('https://images.unsplash.com/photo-1593359677877-a18bb66a8a28?w=800&q=80'),
    category_id: 1,
    category_name: 'Electronics',
    category_name_ar: 'إلكترونيات',
    category_slug: 'electronics',
    stock: 15,
    rating: 4.5,
    reviews_count: 78,
    featured: 0,
    specifications: JSON.stringify({ 'Size': '55"', 'Resolution': '4K UHD', 'HDR': 'Dolby Vision', 'OS': 'Smart TV' }),
    created_at: '2024-04-01',
  },
  {
    id: 6,
    name: 'Portable Bluetooth Speaker',
    name_ar: 'مكبر بلوتوث محمول',
    slug: 'portable-bluetooth-speaker',
    description: 'Compact speaker with 360° sound, 20-hour battery, and IPX7 waterproof rating.',
    description_ar: 'مكبر مدمج بصوت 360 درجة، بطارية 20 ساعة، وتصنيف IPX7 مقاوم للماء.',
    price: 79.99,
    compare_price: 99.99,
    images: img('https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'),
    category_id: 1,
    category_name: 'Electronics',
    category_name_ar: 'إلكترونيات',
    category_slug: 'electronics',
    stock: 200,
    rating: 4.4,
    reviews_count: 312,
    featured: 0,
    specifications: JSON.stringify({ 'Battery': '20 hours', 'Waterproof': 'IPX7', 'Bluetooth': '5.0', 'Weight': '580g' }),
    created_at: '2024-04-15',
  },
  {
    id: 7,
    name: 'Classic Denim Jacket',
    name_ar: 'جاكيت جينز كلاسيكي',
    slug: 'classic-denim-jacket',
    description: 'Timeless denim jacket made from 100% organic cotton. Perfect for any season.',
    description_ar: 'جاكيت جينز خالد مصنوع من قطن عضوي 100%. مثالي لأي موسم.',
    price: 89.00,
    compare_price: 119.00,
    images: img('https://images.unsplash.com/photo-1551028719-320671ce5c87?w=800&q=80'),
    category_id: 2,
    category_name: 'Fashion',
    category_name_ar: 'أزياء',
    category_slug: 'fashion',
    stock: 67,
    rating: 4.5,
    reviews_count: 45,
    featured: 1,
    specifications: JSON.stringify({ 'Material': '100% Cotton', 'Fit': 'Regular', 'Care': 'Machine wash', 'Origin': 'Imported' }),
    created_at: '2024-02-25',
  },
  {
    id: 8,
    name: 'Premium Leather Sneakers',
    name_ar: 'أحذية جلدية فاخرة',
    slug: 'premium-leather-sneakers',
    description: 'Handcrafted leather sneakers with cushioned insoles for all-day comfort.',
    description_ar: 'أحذية جلدية مصنوعة يدوياً مع نعل داخلي مبطّن لراحة طوال اليوم.',
    price: 159.00,
    compare_price: 199.00,
    images: img('https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'),
    category_id: 2,
    category_name: 'Fashion',
    category_name_ar: 'أزياء',
    category_slug: 'fashion',
    stock: 54,
    rating: 4.7,
    reviews_count: 98,
    featured: 1,
    specifications: JSON.stringify({ 'Material': 'Genuine Leather', 'Sole': 'Rubber', 'Sizes': '40-46', 'Color': 'White' }),
    created_at: '2024-03-12',
  },
  {
    id: 9,
    name: 'Minimalist Wrist Watch',
    name_ar: 'ساعة يد بتصميم بسيط',
    slug: 'minimalist-wrist-watch',
    description: 'Elegant stainless steel watch with leather strap. Water-resistant up to 30m.',
    description_ar: 'ساعة ستانلس ستيل أنيقة بحزام جلدي. مقاومة للماء حتى 30 متر.',
    price: 129.00,
    compare_price: 169.00,
    images: img('https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80'),
    category_id: 2,
    category_name: 'Fashion',
    category_name_ar: 'أزياء',
    category_slug: 'fashion',
    stock: 38,
    rating: 4.8,
    reviews_count: 67,
    featured: 0,
    specifications: JSON.stringify({ 'Case': 'Stainless Steel', 'Strap': 'Genuine Leather', 'Water': '30m', 'Movement': 'Quartz' }),
    created_at: '2024-04-08',
  },
  {
    id: 10,
    name: 'Aviator Sunglasses',
    name_ar: 'نظارات شمسية طيار',
    slug: 'aviator-sunglasses',
    description: 'Classic aviator design with UV400 protection and polarized lenses.',
    description_ar: 'تصميم طيار كلاسيكي مع حماية UV400 وعدسات مستقطبة.',
    price: 59.99,
    compare_price: 89.99,
    images: img('https://images.unsplash.com/photo-157263213-1c34b1c5e7b1?w=800&q=80'),
    category_id: 2,
    category_name: 'Fashion',
    category_name_ar: 'أزياء',
    category_slug: 'fashion',
    stock: 145,
    rating: 4.4,
    reviews_count: 132,
    featured: 0,
    specifications: JSON.stringify({ 'Frame': 'Metal', 'Lens': 'Polarized', 'UV': 'UV400', 'Style': 'Aviator' }),
    created_at: '2024-04-20',
  },
  {
    id: 11,
    name: 'Modern Ceramic Vase Set',
    name_ar: 'طقم مزهوجات سيراميك عصري',
    slug: 'modern-ceramic-vase-set',
    description: 'Set of 3 minimalist ceramic vases in neutral tones. Perfect centerpiece for any room.',
    description_ar: 'طقم 3 مزهوجات سيراميك بتصميم بسيط وألوان محايدة. قطعة مركزية مثالية لأي غرفة.',
    price: 49.99,
    compare_price: 69.99,
    images: img('https://images.unsplash.com/photo-1612196198253-5fbdb8a1c5e0?w=800&q=80'),
    category_id: 3,
    category_name: 'Home & Living',
    category_name_ar: 'المنزل والمعيشة',
    category_slug: 'home-living',
    stock: 80,
    rating: 4.6,
    reviews_count: 34,
    featured: 1,
    specifications: JSON.stringify({ 'Material': 'Ceramic', 'Pieces': '3', 'Sizes': 'S/M/L', 'Color': 'Neutral' }),
    created_at: '2024-03-18',
  },
  {
    id: 12,
    name: 'Cozy Throw Blanket',
    name_ar: 'غطاء مريح',
    slug: 'cozy-throw-blanket',
    description: 'Ultra-soft fleece throw blanket, perfect for chilly evenings. Machine washable.',
    description_ar: 'غطاء فليس ناعم جداً، مثالي للأمسيات الباردة. قابل للغسل في الغسالة.',
    price: 39.99,
    compare_price: 54.99,
    images: img('https://images.unsplash.com/photo-1600367668036-38d8c16c91c9?w=800&q=80'),
    category_id: 3,
    category_name: 'Home & Living',
    category_name_ar: 'المنزل والمعيشة',
    category_slug: 'home-living',
    stock: 156,
    rating: 4.7,
    reviews_count: 89,
    featured: 0,
    specifications: JSON.stringify({ 'Material': 'Fleece', 'Size': '130x170cm', 'Care': 'Machine Wash', 'Weight': '1.2kg' }),
    created_at: '2024-04-02',
  },
  {
    id: 13,
    name: 'Aromatic Scented Candle',
    name_ar: 'شمعة عطرية',
    slug: 'aromatic-scented-candle',
    description: 'Soy wax candle with lavender scent. Burns up to 45 hours for long-lasting ambiance.',
    description_ar: 'شمعة شمع الصويا برائحة اللافندر. تحترق حتى 45 ساعة لأجواء تدوم طويلاً.',
    price: 24.99,
    compare_price: 34.99,
    images: img('https://images.unsplash.com/photo-1602874801006-e26c4c5b5e8a?w=800&q=80'),
    category_id: 3,
    category_name: 'Home & Living',
    category_name_ar: 'المنزل والمعيشة',
    category_slug: 'home-living',
    stock: 220,
    rating: 4.5,
    reviews_count: 156,
    featured: 0,
    specifications: JSON.stringify({ 'Wax': 'Soy', 'Scent': 'Lavender', 'Burn': '45 hours', 'Weight': '300g' }),
    created_at: '2024-04-22',
  },
  {
    id: 14,
    name: 'Yoga Mat Premium',
    name_ar: 'سجادة يوغا فاخرة',
    slug: 'yoga-mat-premium',
    description: 'Non-slip eco-friendly yoga mat with carrying strap. 6mm thick for extra comfort.',
    description_ar: 'سجادة يوغا صديقة للبيئة غير قابلة للانزلاق مع حامل. سماكة 6 مم لراحة إضافية.',
    price: 44.99,
    compare_price: 59.99,
    images: img('https://images.unsplash.com/photo-1601925260368-ae2f83cf58b6?w=800&q=80'),
    category_id: 4,
    category_name: 'Sports',
    category_name_ar: 'رياضة',
    category_slug: 'sports',
    stock: 95,
    rating: 4.6,
    reviews_count: 78,
    featured: 1,
    specifications: JSON.stringify({ 'Thickness': '6mm', 'Material': 'Eco TPE', 'Size': '183x61cm', 'Feature': 'Non-slip' }),
    created_at: '2024-03-25',
  },
  {
    id: 15,
    name: 'Adjustable Dumbbell Set',
    name_ar: 'طقم دمبل قابل للتعديل',
    slug: 'adjustable-dumbbell-set',
    description: 'Space-saving adjustable dumbbells, 5-25 kg per hand. Perfect for home workouts.',
    description_ar: 'دمبل قابل للتعديل يوفر مساحة، 5-25 كجم لكل يد. مثالي لتمارين المنزل.',
    price: 199.00,
    compare_price: 279.00,
    images: img('https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=800&q=80'),
    category_id: 4,
    category_name: 'Sports',
    category_name_ar: 'رياضة',
    category_slug: 'sports',
    stock: 32,
    rating: 4.8,
    reviews_count: 54,
    featured: 0,
    specifications: JSON.stringify({ 'Weight': '5-25kg', 'Material': 'Steel', 'Adjustable': 'Yes', 'Grip': 'Anti-slip' }),
    created_at: '2024-04-10',
  },
  {
    id: 16,
    name: 'Running Shoes Air Max',
    name_ar: 'حذاء رياضي Air Max',
    slug: 'running-shoes-air-max',
    description: 'Lightweight running shoes with air cushion technology for maximum comfort.',
    description_ar: 'حذاء رياضي خفيف بتقنية وسادة هوائية لراحة قصوى.',
    price: 129.99,
    compare_price: 169.99,
    images: img('https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'),
    category_id: 4,
    category_name: 'Sports',
    category_name_ar: 'رياضة',
    category_slug: 'sports',
    stock: 88,
    rating: 4.7,
    reviews_count: 145,
    featured: 0,
    specifications: JSON.stringify({ 'Sole': 'Air Cushion', 'Weight': '280g', 'Sizes': '40-46', 'Use': 'Running' }),
    created_at: '2024-04-18',
  },
  {
    id: 17,
    name: 'Luxury Skincare Set',
    name_ar: 'مجموعة العناية بالبشرة الفاخرة',
    slug: 'luxury-skincare-set',
    description: 'Complete skincare routine: cleanser, toner, serum, and moisturizer for glowing skin.',
    description_ar: 'روتين كامل للعناية بالبشرة: منظف، تونر، سيروم، ومرطب لبشرة مشرقة.',
    price: 149.00,
    compare_price: 199.00,
    images: img('https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80'),
    category_id: 5,
    category_name: 'Beauty',
    category_name_ar: 'جمال',
    category_slug: 'beauty',
    stock: 60,
    rating: 4.9,
    reviews_count: 234,
    featured: 1,
    specifications: JSON.stringify({ 'Pieces': '4', 'Skin': 'All types', 'Volume': '200ml total', 'Type': 'Vegan' }),
    created_at: '2024-03-30',
  },
  {
    id: 18,
    name: 'Matte Lipstick Collection',
    name_ar: 'مجموعة أحمر شفاه مطفي',
    slug: 'matte-lipstick-collection',
    description: 'Set of 6 long-lasting matte lipsticks in trending nude shades.',
    description_ar: 'طقم 6 أحمر شفاه مطفي طويل الأمد بألوان عصرية.',
    price: 34.99,
    compare_price: 49.99,
    images: img('https://images.unsplash.com/photo-1586495777744-441040824b3a?w=800&q=80'),
    category_id: 5,
    category_name: 'Beauty',
    category_name_ar: 'جمال',
    category_slug: 'beauty',
    stock: 175,
    rating: 4.5,
    reviews_count: 167,
    featured: 0,
    specifications: JSON.stringify({ 'Pieces': '6', 'Finish': 'Matte', 'Net': '3.5g each', 'Cruelty': 'Free' }),
    created_at: '2024-04-12',
  },
  {
    id: 19,
    name: 'Bestseller Novel: The Midnight Library',
    name_ar: 'رواية الأكثر مبيعاً: مكتبة منتصف الليل',
    slug: 'bestseller-midnight-library',
    description: 'A dazzling novel about all the choices that go into a life well lived by Matt Haig.',
    description_ar: 'رواية ساحرة عن كل الخيارات التي تصنع حياةً ذات معنى بقلم مات هَيغ.',
    price: 18.99,
    compare_price: 24.99,
    images: img('https://images.unsplash.com/photo-1544947950-fa07a3d8b2c4?w=800&q=80'),
    category_id: 6,
    category_name: 'Books',
    category_name_ar: 'كتب',
    category_slug: 'books',
    stock: 250,
    rating: 4.8,
    reviews_count: 1240,
    featured: 1,
    specifications: JSON.stringify({ 'Author': 'Matt Haig', 'Pages': '304', 'Language': 'English', 'Format': 'Paperback' }),
    created_at: '2024-01-20',
  },
  {
    id: 20,
    name: 'Cookbook: Modern Home Cooking',
    name_ar: 'كتاب طبخ: الطبخ المنزلي العصري',
    slug: 'cookbook-modern-home-cooking',
    description: '300+ recipes for everyday meals with beautiful photography and easy instructions.',
    description_ar: 'أكثر من 300 وصفة لوجبات يومية مع صور رائعة وتعليمات سهلة.',
    price: 29.99,
    compare_price: 39.99,
    images: img('https://images.unsplash.com/photo-1544716278-ca5e3164c9e8?w=800&q=80'),
    category_id: 6,
    category_name: 'Books',
    category_name_ar: 'كتب',
    category_slug: 'books',
    stock: 120,
    rating: 4.6,
    reviews_count: 87,
    featured: 0,
    specifications: JSON.stringify({ 'Recipes': '300+', 'Pages': '450', 'Language': 'English', 'Format': 'Hardcover' }),
    created_at: '2024-04-05',
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    product_id: 1,
    user_id: 1,
    user_name: 'Sarah Johnson',
    user_avatar: 'https://i.pravatar.cc/100?img=1',
    rating: 5,
    comment: 'Best headphones I have ever owned! The noise cancellation is incredible.',
    created_at: '2024-03-15',
  },
  {
    id: 2,
    product_id: 1,
    user_id: 2,
    user_name: 'Ahmed Ali',
    user_avatar: 'https://i.pravatar.cc/100?img=12',
    rating: 4,
    comment: 'Great sound quality but a bit pricey. Still worth it.',
    created_at: '2024-04-02',
  },
  {
    id: 3,
    product_id: 2,
    user_id: 3,
    user_name: 'John Smith',
    user_avatar: 'https://i.pravatar.cc/100?img=33',
    rating: 5,
    comment: 'Perfect for tracking my daily workouts. The display is bright and clear.',
    created_at: '2024-03-20',
  },
  {
    id: 4,
    product_id: 8,
    user_id: 4,
    user_name: 'Maria Garcia',
    user_avatar: 'https://i.pravatar.cc/100?img=45',
    rating: 5,
    comment: 'Super comfortable and stylish. I get compliments every time I wear them.',
    created_at: '2024-04-10',
  },
  {
    id: 5,
    product_id: 19,
    user_id: 5,
    user_name: 'David Kim',
    user_avatar: 'https://i.pravatar.cc/100?img=68',
    rating: 5,
    comment: 'One of the best books I have ever read. Could not put it down!',
    created_at: '2024-02-28',
  },
];

export function getMockFeatured(): Product[] {
  return mockProducts.filter((p) => p.featured === 1);
}

export function getMockProductBySlug(slug: string): { product: Product | undefined; reviews: Review[]; related: Product[] } {
  const product = mockProducts.find((p) => p.slug === slug);
  if (!product) return { product: undefined, reviews: [], related: [] };
  const reviews = mockReviews.filter((r) => r.product_id === product.id);
  const related = mockProducts.filter((p) => p.category_id === product.category_id && p.id !== product.id).slice(0, 4);
  return { product, reviews, related };
}

export function getMockProducts(params: Record<string, string> = {}): { products: Product[]; pagination: Pagination } {
  let products = [...mockProducts];

  const category = params.category;
  if (category) {
    products = products.filter((p) => p.category_slug === category);
  }

  const search = params.search;
  if (search) {
    const q = search.toLowerCase();
    products = products.filter((p) => p.name.toLowerCase().includes(q) || p.description!.toLowerCase().includes(q));
  }

  const featured = params.featured;
  if (featured === 'true') {
    products = products.filter((p) => p.featured === 1);
  }

  const sort = params.sort;
  if (sort === 'price_asc') products.sort((a, b) => a.price - b.price);
  else if (sort === 'price_desc') products.sort((a, b) => b.price - a.price);
  else if (sort === 'rating') products.sort((a, b) => b.rating - a.rating);

  const page = parseInt(params.page || '1');
  const limit = 12;
  const total = products.length;
  const totalPages = Math.max(1, Math.ceil(total / limit));
  const start = (page - 1) * limit;
  const paged = products.slice(start, start + limit);

  return {
    products: paged,
    pagination: { page, limit, total, totalPages },
  };
}

type Pagination = { page: number; limit: number; total: number; totalPages: number };
