import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Locale = 'en' | 'ar' | 'fr' | 'es' | 'de' | 'tr' | 'ur' | 'hi' | 'zh' | 'ja' | 'ko';

const RTL_LOCALES = new Set(['ar', 'ur']);

interface LanguageContextType {
  locale: Locale;
  setLocale: (l: Locale) => void;
  dir: 'ltr' | 'rtl';
  t: (key: string) => string;
  locales: { code: Locale; label: string; flag: string }[];
}

const localesList: { code: Locale; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
  { code: 'ur', label: 'اردو', flag: '🇵🇰' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
];

const translations: Record<Locale, { [key: string]: string }> = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.signin': 'Sign In',
    'nav.search': 'Search products, categories, brands...',
    'nav.profile': 'Profile',
    'nav.orders': 'Orders',
    'nav.logout': 'Logout',
    'nav.cart': 'Cart',
    'hero.badge': 'Premium Collection 2026',
    'hero.title1': 'Discover',
    'hero.title2': 'Premium',
    'hero.title3': 'Products',
    'hero.desc': 'Shop the latest trends with confidence. Quality products, fast delivery, and exceptional service — all in one place.',
    'hero.cta': 'Start Shopping',
    'hero.learn': 'Learn More',
    'hero.trusted': 'Trusted by',
    'hero.customers': 'Customers',
    'feature.shipping': 'Free Shipping',
    'feature.shipping_desc': 'Orders over $200',
    'feature.payment': 'Secure Payment',
    'feature.payment_desc': '100% protected',
    'feature.support': '24/7 Support',
    'feature.support_desc': 'Dedicated team',
    'feature.returns': 'Easy Returns',
    'feature.returns_desc': '30-day guarantee',
    'categories.title': 'Shop by Category',
    'categories.subtitle': 'Explore our curated collections',
    'categories.viewall': 'View All',
    'featured.title': 'Popular Products',
    'featured.subtitle': 'Featured',
    'brands.title': 'Trusted By Leading Brands',
    'brands.subtitle': 'Our Partners',
    'cta.title': 'Ready to Shop Premium?',
    'cta.desc': 'Join thousands of happy customers. Get exclusive deals, early access, and premium support.',
    'cta.button': 'Get Started Free',
    'cta.free': 'Free Shipping',
    'cta.prices': 'Best Prices',
    'cta.support': 'Premium Support',
    'cta.returns': 'Easy Returns',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to access your account, manage orders, and continue your shopping journey with us.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgot': 'Forgot password?',
    'login.button': 'Sign In',
    'login.loading': 'Signing in...',
    'login.noaccount': "Don't have an account?",
    'login.create': 'Create Account',
    'login.or': 'or continue with',
    'login.demo': 'Demo Credentials',
    'login.demo_admin': 'Admin',
    'login.demo_user': 'User',
    'register.title': 'Join ShopPro',
    'register.subtitle': 'Create your account and unlock a world of premium products, exclusive deals, and seamless shopping.',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.button': 'Create Account',
    'register.loading': 'Creating Account...',
    'register.haveaccount': 'Already have an account?',
    'register.signin': 'Sign in',
    'register.terms': 'By signing up, you agree to our',
    'register.terms_link': 'Terms',
    'register.privacy': 'Privacy Policy',
    'footer.desc': 'Your premium destination for quality products. We bring you the best brands at unbeatable prices with exceptional service.',
    'footer.quicklinks': 'Quick Links',
    'footer.categories': 'Categories',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'items': 'items',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.admin': 'لوحة التحكم',
    'nav.signin': 'تسجيل الدخول',
    'nav.search': 'ابحث عن منتجات، تصنيفات، علامات تجارية...',
    'nav.profile': 'الملف الشخصي',
    'nav.orders': 'الطلبات',
    'nav.logout': 'تسجيل الخروج',
    'nav.cart': 'السلة',
    'hero.badge': 'مجموعة بريميوم 2026',
    'hero.title1': 'اكتشف',
    'hero.title2': 'ممتاز',
    'hero.title3': 'منتجات',
    'hero.desc': 'تسوق أحدث الصيحات بثقة. منتجات عالية الجودة، توصيل سريع، وخدمة استثنائية - كل ذلك في مكان واحد.',
    'hero.cta': 'ابدأ التسوق',
    'hero.learn': 'اعرف المزيد',
    'hero.trusted': 'موثوق من',
    'hero.customers': 'عميل',
    'feature.shipping': 'شحن مجاني',
    'feature.shipping_desc': 'للطلبات فوق 200$',
    'feature.payment': 'دفع آمن',
    'feature.payment_desc': 'محمي 100%',
    'feature.support': 'دعم 24/7',
    'feature.support_desc': 'فريق متخصص',
    'feature.returns': 'إرجاع سهل',
    'feature.returns_desc': 'ضمان 30 يوم',
    'categories.title': 'تسوق حسب التصنيف',
    'categories.subtitle': 'استكشف مجموعاتنا المختارة',
    'categories.viewall': 'عرض الكل',
    'featured.title': 'المنتجات الشائعة',
    'featured.subtitle': 'مميز',
    'brands.title': 'موثوق من علامات رائدة',
    'brands.subtitle': 'شركاؤنا',
    'cta.title': 'هل أنت مستعد للتسوق الممتاز؟',
    'cta.desc': 'انضم إلى آلاف العملاء السعداء. احصل على عروض حصرية ووصول مبكر ودعم ممتاز.',
    'cta.button': 'ابدأ مجاناً',
    'cta.free': 'شحن مجاني',
    'cta.prices': 'أفضل الأسعار',
    'cta.support': 'دعم ممتاز',
    'cta.returns': 'إرجاع سهل',
    'login.title': 'مرحباً بعودتك',
    'login.subtitle': 'سجل الدخول للوصول إلى حسابك وإدارة طلباتك ومتابعة رحلة التسوق معنا.',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.forgot': 'نسيت كلمة المرور؟',
    'login.button': 'تسجيل الدخول',
    'login.loading': 'جاري تسجيل الدخول...',
    'login.noaccount': 'ليس لديك حساب؟',
    'login.create': 'إنشاء حساب',
    'login.or': 'أو المتابعة عبر',
    'login.demo': 'بيانات الدخول التجريبية',
    'login.demo_admin': 'مدير',
    'login.demo_user': 'مستخدم',
    'register.title': 'انضم إلى ShopPro',
    'register.subtitle': 'أنشئ حسابك وافتح عالمًا من المنتجات الممتازة والصفقات الحصرية والتسوق السلس.',
    'register.name': 'الاسم الكامل',
    'register.email': 'البريد الإلكتروني',
    'register.password': 'كلمة المرور',
    'register.button': 'إنشاء حساب',
    'register.loading': 'جاري إنشاء الحساب...',
    'register.haveaccount': 'هل لديك حساب بالفعل؟',
    'register.signin': 'تسجيل الدخول',
    'register.terms': 'بالتسجيل، أنت توافق على',
    'register.terms_link': 'الشروط',
    'register.privacy': 'سياسة الخصوصية',
    'footer.desc': 'وجهتك الممتازة للمنتجات عالية الجودة. نقدم لك أفضل العلامات التجارية بأسعار لا تقبل المنافسة مع خدمة استثنائية.',
    'footer.quicklinks': 'روابط سريعة',
    'footer.categories': 'التصنيفات',
    'footer.contact': 'اتصل بنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'سياسة ملفات تعريف الارتباط',
    'items': 'منتجات',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.signin': 'Connexion',
    'hero.badge': 'Collection Premium 2026',
    'hero.title1': 'Découvrez',
    'hero.title2': 'Premium',
    'hero.title3': 'Produits',
    'hero.desc': 'Achetez les dernières tendances en toute confiance. Produits de qualité, livraison rapide et service exceptionnel - tout en un seul endroit.',
    'hero.cta': 'Commencer',
    'categories.title': 'Achat par catégorie',
    'featured.title': 'Produits populaires',
    'brands.title': 'Marques de confiance',
    'cta.title': 'Prêt à acheter Premium?',
    'footer.rights': 'Tous droits réservés.',
    'items': 'articles',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.products': 'Productos',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.signin': 'Iniciar sesión',
    'hero.badge': 'Colección Premium 2026',
    'hero.title1': 'Descubre',
    'hero.title2': 'Premium',
    'hero.title3': 'Productos',
    'hero.desc': 'Compra las últimas tendencias con confianza. Productos de calidad, entrega rápida y servicio excepcional, todo en un solo lugar.',
    'hero.cta': 'Empezar',
    'categories.title': 'Comprar por categoría',
    'featured.title': 'Productos populares',
    'brands.title': 'Marcas líderes',
    'cta.title': '¿Listo para comprar Premium?',
    'footer.rights': 'Todos los derechos reservados.',
    'items': 'artículos',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.products': 'Produkte',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.signin': 'Anmelden',
    'hero.badge': 'Premium-Kollektion 2026',
    'hero.title1': 'Entdecken',
    'hero.title2': 'Premium',
    'hero.title3': 'Produkte',
    'hero.desc': 'Kaufen Sie die neuesten Trends mit Vertrauen. Qualitätsprodukte, schnelle Lieferung und außergewöhnlicher Service - alles an einem Ort.',
    'hero.cta': 'Loslegen',
    'categories.title': 'Nach Kategorie',
    'featured.title': 'Beliebte Produkte',
    'brands.title': 'Führende Marken',
    'cta.title': 'Bereit für Premium-Einkäufe?',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'items': 'Artikel',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.products': 'Ürünler',
    'nav.about': 'Hakkımızda',
    'nav.contact': 'İletişim',
    'nav.signin': 'Giriş Yap',
    'hero.badge': 'Premium Koleksiyon 2026',
    'hero.title1': 'Keşfet',
    'hero.title2': 'Premium',
    'hero.title3': 'Ürünler',
    'hero.desc': 'En son trendleri güvenle alışveriş yapın. Kaliteli ürünler, hızlı teslimat ve olağanüstü hizmet - hepsi tek bir yerde.',
    'hero.cta': 'Başla',
    'categories.title': 'Kategoriye Göre Alışveriş',
    'featured.title': 'Popüler Ürünler',
    'brands.title': 'Lider Markalar',
    'cta.title': 'Premium Alışverişe Hazır mısınız?',
    'footer.rights': 'Tüm hakları saklıdır.',
    'items': 'ürünler',
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.products': 'مصنوعات',
    'nav.about': 'ہمارے بارے میں',
    'nav.contact': 'رابطہ',
    'nav.signin': 'سائن ان',
    'hero.badge': 'پریمیم کلیکشن 2026',
    'hero.title1': 'دریافت کریں',
    'hero.title2': 'پریمیم',
    'hero.title3': 'مصنوعات',
    'hero.desc': 'اعتماد کے ساتھ تازہ ترین رجحانات خریدیں۔ معیاری مصنوعات، تیز ترسیل، اور غیر معمولی سروس - سب ایک جگہ۔',
    'hero.cta': 'شاپنگ شروع کریں',
    'categories.title': 'زمرہ کے مطابق خریدیں',
    'featured.title': 'مشہور مصنوعات',
    'brands.title': 'معروف برانڈز',
    'cta.title': 'پریمیم شاپنگ کے لیے تیار ہیں؟',
    'footer.rights': 'جملہ حقوق محفوظ ہیں۔',
    'items': 'اشیاء',
  },
  hi: {
    'nav.home': 'होम',
    'nav.products': 'उत्पाद',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क',
    'nav.signin': 'साइन इन',
    'hero.badge': 'प्रीमियम कलेक्शन 2026',
    'hero.title1': 'खोजें',
    'hero.title2': 'प्रीमियम',
    'hero.title3': 'उत्पाद',
    'hero.desc': 'नवीनतम ट्रेंड्स को आत्मविश्वास से खरीदें। गुणवत्ता वाले उत्पाद, तेज़ डिलीवरी, और असाधारण सेवा - सब एक ही जगह।',
    'hero.cta': 'शुरू करें',
    'categories.title': 'श्रेणी के अनुसार खरीदें',
    'featured.title': 'लोकप्रिय उत्पाद',
    'brands.title': 'प्रमुख ब्रांड',
    'cta.title': 'प्रीमियम खरीदारी के लिए तैयार?',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'items': 'आइटम',
  },
  zh: {
    'nav.home': '首页',
    'nav.products': '产品',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.signin': '登录',
    'hero.badge': '2026 高级系列',
    'hero.title1': '发现',
    'hero.title2': '高级',
    'hero.title3': '产品',
    'hero.desc': '自信地购买最新潮流。优质产品、快速配送和卓越服务 - 一站式购物体验。',
    'hero.cta': '开始购物',
    'categories.title': '按类别购物',
    'featured.title': '热门产品',
    'brands.title': '领先品牌信赖',
    'cta.title': '准备好高级购物了吗？',
    'footer.rights': '保留所有权利。',
    'items': '件商品',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.products': '製品',
    'nav.about': '私たちについて',
    'nav.contact': 'お問い合わせ',
    'nav.signin': 'サインイン',
    'hero.badge': 'プレミアムコレクション2026',
    'hero.title1': '発見する',
    'hero.title2': 'プレミアム',
    'hero.title3': '製品',
    'hero.desc': '最新のトレンドを自信を持ってお買い求めください。高品質な製品、迅速な配送、卓越したサービス - すべてがひとつに。',
    'hero.cta': '買い物を始める',
    'categories.title': 'カテゴリーから探す',
    'featured.title': '人気商品',
    'brands.title': '主要ブランド',
    'cta.title': 'プレミアムショッピングの準備はできましたか？',
    'footer.rights': '全著作権所有。',
    'items': 'アイテム',
  },
  ko: {
    'nav.home': '홈',
    'nav.products': '제품',
    'nav.about': '소개',
    'nav.contact': '문의',
    'nav.signin': '로그인',
    'hero.badge': '프리미엄 컬렉션 2026',
    'hero.title1': '발견',
    'hero.title2': '프리미엄',
    'hero.title3': '제품',
    'hero.desc': '최신 트렌드를 자신 있게 쇼핑하세요. 품질 제품, 빠른 배송, 탁월한 서비스 - 모든 것이 한 곳에.',
    'hero.cta': '쇼핑 시작',
    'categories.title': '카테고리별 쇼핑',
    'featured.title': '인기 제품',
    'brands.title': '선도 브랜드',
    'cta.title': '프리미엄 쇼핑을 준비하셨나요?',
    'footer.rights': '모든 권리 보유.',
    'items': '개',
  },
};

const FALLBACK_LOCALE = 'en';

export function t(locale: Locale, key: string): string {
  return translations[locale]?.[key] ?? translations[FALLBACK_LOCALE]?.[key] ?? key;
}

const LanguageContext = createContext<LanguageContextType>({
  locale: 'en',
  setLocale: () => {},
  dir: 'ltr',
  t: (key: string) => key,
  locales: localesList,
});
export const useLang = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    const stored = localStorage.getItem('locale') as Locale | null;
    if (stored && localesList.some((l) => l.code === stored)) return stored;
    const browserLang = navigator.language.slice(0, 2).toLowerCase();
    if (localesList.some((l) => l.code === browserLang)) return browserLang as Locale;
    return 'en';
  });

  const dir = RTL_LOCALES.has(locale) ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = locale;
    localStorage.setItem('locale', locale);
  }, [locale, dir]);

  const translate = (key: string) => t(locale, key);

  return (
    <LanguageContext.Provider value={{ locale, setLocale, dir, t: translate, locales: localesList }}>
      {children}
    </LanguageContext.Provider>
  );
}
